import { spawn } from 'node:child_process';
import { readFile, mkdir, mkdtemp, readdir, writeFile, access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { runMediaSmoke } from './media-smoke.mjs';
import { runIPhoneSmoke } from './iphone-smoke.mjs';
import { runPwaSmoke } from './pwa-smoke.mjs';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const artifacts=join(root,'tests','artifacts');
await mkdir(artifacts,{recursive:true});
const downloads=await mkdtemp(join(artifacts,'downloads-'));
const profile=await mkdtemp(join(tmpdir(),'feature-lens-test-'));
const candidates=[process.env.CHROME_PATH,'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe','/usr/bin/google-chrome','/usr/bin/chromium'].filter(Boolean);
let executable;
for(const candidate of candidates){try{await access(candidate);executable=candidate;break;}catch{}}
if(!executable)throw new Error('Set CHROME_PATH to a Chrome or Edge executable.');
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(fn,label,timeout=15000){const end=Date.now()+timeout;while(Date.now()<end){const value=await fn();if(value)return value;await delay(100);}throw new Error(`Timed out: ${label}`);}
const server=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,PORT:'0'},windowsHide:true,stdio:['ignore','pipe','pipe']});
let serverOutput='';server.stdout.on('data',data=>serverOutput+=data);
let browser,ws;
try {
  const url=await until(()=>serverOutput.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0],'server startup');
  assert.equal((await fetch(`${url}/missing`)).status,404);
  assert.equal((await fetch(url,{method:'POST'})).status,405);
  browser=spawn(executable,['--headless=new','--no-sandbox','--disable-gpu','--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--disable-background-networking','--disable-extensions','--no-first-run','--no-default-browser-check','--window-size=1440,1100','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
  const port=await until(async()=>{try{return Number((await readFile(join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0]);}catch{return false;}},'browser startup');
  const tabs=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  ws=new WebSocket(tabs.find(tab=>tab.type==='page').webSocketDebuggerUrl);
  await new Promise((resolve,reject)=>{ws.addEventListener('open',resolve,{once:true});ws.addEventListener('error',reject,{once:true});});
  let nextId=0;const requests=new Map(),errors=[];
  ws.addEventListener('message',event=>{
    const data=JSON.parse(event.data);
    if(data.id){const item=requests.get(data.id);if(item){requests.delete(data.id);clearTimeout(item.timer);data.error?item.reject(new Error(JSON.stringify(data.error))):item.resolve(data.result);}}
    if(data.method==='Runtime.exceptionThrown')errors.push(data.params.exceptionDetails.text+': '+(data.params.exceptionDetails.exception?.description||''));
    if(data.method==='Log.entryAdded'&&data.params.entry.level==='error'&&!data.params.entry.text.includes('404'))errors.push(data.params.entry.text);
  });
  function send(method,params={}){return new Promise((resolve,reject)=>{const id=++nextId;const timer=setTimeout(()=>{requests.delete(id);reject(new Error(`CDP timeout: ${method}`));},15000);requests.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}));});}
  async function evaluate(expression){const data=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(data.exceptionDetails)throw new Error(data.exceptionDetails.exception?.description||data.exceptionDetails.text);return data.result.value;}
  const click=id=>evaluate(`document.getElementById(${JSON.stringify(id)}).click()`);
  const waitFor=async(expression,label)=>{try{return await until(()=>evaluate(expression),label);}catch(error){console.error('Browser diagnostics:',errors,await evaluate("({status:document.getElementById('status')?.textContent,object:document.getElementById('objectStatus')?.textContent,preview:{...document.getElementById('preview')?.dataset},video:document.getElementById('fileVideo')?{ready:document.getElementById('fileVideo').readyState,seeking:document.getElementById('fileVideo').seeking,time:document.getElementById('fileVideo').currentTime,paused:document.getElementById('fileVideo').paused}:null})"));throw error;}};
  await send('Page.enable');await send('Runtime.enable');await send('Log.enable');
  await send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads});
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
  await send('Page.navigate',{url});
  await waitFor("document.readyState==='complete' && !!document.getElementById('emptyDemo')",'page load');
  await click('emptyDemo');
  await waitFor("Number(document.getElementById('pointCount').textContent)>20",'demo detection');
  await waitFor("Number(document.getElementById('fps').textContent)>0",'FPS metric');
  await writeFile(join(artifacts,'desktop-demo.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
  console.log('PASS: demo renders detected points and live metrics');
  const rates={};
  for(const rate of [60,30]){
    await evaluate(`document.getElementById('targetFps').value='${rate}';document.getElementById('targetFps').dispatchEvent(new Event('change'))`);
    rates[rate]=await evaluate("new Promise(resolve=>{const start=performance.now();let frames=0;const observer=new MutationObserver(records=>{frames+=records.length;});observer.observe(document.getElementById('preview'),{attributes:true,attributeFilter:['data-detected-count']});setTimeout(()=>{observer.disconnect();resolve(Number((frames*1000/(performance.now()-start)).toFixed(1)));},1800);})");
    assert(rates[rate]>0 && rates[rate]<rate*1.2,`frame cap ${rate}: ${rates[rate]}`);
  }
  await writeFile(join(artifacts,'frame-rates.json'),JSON.stringify(rates,null,2));
  console.log('MEASURE: completed demo frames/sec at 60/30 caps:',rates);
  await evaluate("document.getElementById('targetFps').value='60';document.getElementById('targetFps').dispatchEvent(new Event('change'))");
  await evaluate("document.getElementById('originalFile').dispatchEvent(new Event('click'))");
  await delay(150);
  assert.equal(await evaluate("new Promise(resolve=>{let frames=0;const observer=new MutationObserver(records=>{frames+=records.length;});observer.observe(document.getElementById('preview'),{attributes:true,attributeFilter:['data-detected-count']});setTimeout(()=>{observer.disconnect();resolve(frames);},250);})"),0);
  await evaluate("document.getElementById('originalFile').dispatchEvent(new Event('cancel'))");
  await waitFor("new Promise(resolve=>{const observer=new MutationObserver(()=>{observer.disconnect();resolve(true)});observer.observe(document.getElementById('preview'),{attributes:true,attributeFilter:['data-detected-count']});setTimeout(()=>{observer.disconnect();resolve(false)},200);})",'picker cancellation resumes analysis');
  console.log('PASS: file picker suspends processing and cancellation resumes it');
  await evaluate("document.getElementById('algorithm').value='harris';document.getElementById('maxPoints').value='25';document.getElementById('maxPoints').dispatchEvent(new Event('input'))");
  await waitFor("document.getElementById('frameTag').textContent==='HARRIS' && Number(document.getElementById('pointCount').textContent)<=25",'settings update');
  console.log('PASS: Harris and maximum point count update live');
  await click('stop');
  const stable=await evaluate("document.getElementById('preview').toDataURL()");
  await click('mirror');assert.notEqual(await evaluate("document.getElementById('preview').toDataURL()"),stable);
  await click('mirror');assert.equal(await evaluate("document.getElementById('preview').toDataURL()"),stable);
  await click('showPoints');assert.notEqual(await evaluate("document.getElementById('preview').toDataURL()"),stable);
  await click('showPoints');assert.equal(await evaluate("document.getElementById('preview').toDataURL()"),stable);
  console.log('PASS: mirror and point visibility redraw the stopped frame');
  await click('savePoints');await click('saveImage');
  const jsonName=await until(async()=>(await readdir(downloads)).find(name=>name.endsWith('.json')),'JSON download');
  const pngName=await until(async()=>(await readdir(downloads)).find(name=>name.endsWith('.png')),'PNG download');
  const exported=JSON.parse(await readFile(join(downloads,jsonName),'utf8'));
  assert.equal(exported.algorithm,'harris');assert(exported.points.length>0&&exported.points.length<=25);
  assert(exported.points.every(p=>p.x>=0&&p.x<exported.image.width&&p.y>=0&&p.y<exported.image.height));
  const png=await readFile(join(downloads,pngName));assert.equal(png.readUInt32BE(16),1280);assert.equal(png.readUInt32BE(20),720);
  console.log('PASS: PNG and original-image JSON coordinates download correctly');
  await evaluate("document.getElementById('algorithm').value='shi-tomasi';document.getElementById('maxPoints').value='250';document.getElementById('maxPoints').dispatchEvent(new Event('input'))");
  await click('tech-trails');
  await waitFor("/継続 [1-9]/.test(document.getElementById('demoStats').textContent)",'feature trajectories');
  await delay(700);
  await writeFile(join(artifacts,'tracking-demo.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await click('resetTracking');
  await waitFor("/継続 [1-9]/.test(document.getElementById('demoStats').textContent)",'reset then resume');
  await click('tech-flow');
  await waitFor("/対応 [1-9]/.test(document.getElementById('demoStats').textContent)",'flow vectors');
  await delay(300);
  await writeFile(join(artifacts,'flow-demo.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await click('stop');await click('savePoints');
  const flowName=await until(async()=>{for(const name of await readdir(downloads)){if(name.endsWith('.json')&&name!==jsonName){try{if(JSON.parse(await readFile(join(downloads,name),'utf8')).technique==='flow')return name;}catch{}}}return false;},'flow export');
  const flow=JSON.parse(await readFile(join(downloads,flowName),'utf8'));
  assert(flow.tracks.some(t=>t.age>1&&t.trail.length>1));assert(flow.motion.matched>0);
  assert(flow.tracks.every(t=>Number.isFinite(t.dx)&&Number.isFinite(t.dy)));
  console.log('PASS: tracks, optical flow, reset, and motion export');
  await click('tech-density');
  await waitFor("document.getElementById('demoStats').textContent.includes('区画')",'density heatmap');
  await click('highDetail');
  await waitFor("document.getElementById('analysisResolution').textContent==='1920 × 1080' && document.getElementById('resolution').textContent==='1920 × 1080'",'full-HD analysis');
  assert.equal(await evaluate("document.getElementById('maxPoints').value"),'1500');
  await writeFile(join(artifacts,'density-full-hd.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await evaluate("document.getElementById('inputResolution').value='3840';document.getElementById('inputResolution').dispatchEvent(new Event('change'))");
  await waitFor("document.getElementById('resolution').textContent==='3840 × 2160' && document.getElementById('analysisResolution').textContent==='1920 × 1080'",'4K input with full-HD analysis');
  await evaluate("document.getElementById('inputResolution').value='1280';document.getElementById('inputResolution').dispatchEvent(new Event('change'))");
  await waitFor("document.getElementById('analysisResolution').textContent==='1280 × 720' && document.getElementById('qualityNotice').textContent.includes('上限')",'no upscaling beyond source');
  console.log('PASS: density map, full-HD preset, 4K input, and source resolution cap');
  await click('tech-trails');
  await evaluate("document.getElementById('demoScene').value='detail';document.getElementById('demoScene').dispatchEvent(new Event('change'));document.getElementById('processingWidth').value='640';document.getElementById('processingWidth').dispatchEvent(new Event('change'));document.getElementById('maxPoints').value='1000';document.getElementById('maxPoints').dispatchEvent(new Event('input'));document.getElementById('minDistance').value='4';document.getElementById('minDistance').dispatchEvent(new Event('input'))");
  await waitFor("Number(document.getElementById('preview').dataset.trackCount)>500 && Number(document.getElementById('preview').dataset.detectedCount)>500",'more than 250 tracks');
  await writeFile(join(artifacts,'dense-trails.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await click('tech-flow');
  await evaluate("document.getElementById('demoScene').value='detail';document.getElementById('demoScene').dispatchEvent(new Event('change'))");
  await waitFor("document.getElementById('preview').dataset.technique==='flow' && Number(document.getElementById('preview').dataset.trackCount)>500",'dense flow points');
  console.log('PASS: trail and vector displays honor the requested count beyond 250 points');
  await evaluate("document.getElementById('minDistance').value='10';document.getElementById('minDistance').dispatchEvent(new Event('input'))");
  await evaluate("document.getElementById('processingWidth').value='480';document.getElementById('processingWidth').dispatchEvent(new Event('change'));document.getElementById('maxPoints').value='250'");
  await click('tech-points');
  await evaluate("window.nativeGetUserMedia=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=constraints=>{window.requestedCamera=constraints;return window.nativeGetUserMedia(constraints)}");
  await click('start');
  await waitFor("document.getElementById('preview').dataset.source==='camera' && Number(document.getElementById('pointCount').textContent)>0 && document.getElementById('video').srcObject?.active",'synthetic camera');
  assert.equal(await evaluate("window.requestedCamera.video.frameRate.ideal"),60);
  await evaluate("window.testTrack=document.getElementById('video').srcObject.getVideoTracks()[0]");
  await click('tech-flow');
  await waitFor("document.getElementById('preview').dataset.source==='camera' && document.getElementById('preview').dataset.technique==='flow'",'camera technique switch');
  assert.equal(await evaluate("window.testTrack===document.getElementById('video').srcObject.getVideoTracks()[0]"),true);
  await click('highDetail');
  await waitFor("window.requestedCamera.video.width.ideal===1920 && document.getElementById('video').srcObject?.active && document.getElementById('analysisResolution').textContent==='1920 × 1080'",'camera full-HD restart');
  assert.equal(await evaluate("window.testTrack.readyState"),'ended');
  await evaluate("window.testTrack=document.getElementById('video').srcObject.getVideoTracks()[0]");
  console.log('PASS: technique switch keeps the live camera; full-HD requests restart it');
  await evaluate("document.getElementById('targetFps').value='30';document.getElementById('targetFps').dispatchEvent(new Event('change'))");
  await waitFor("window.requestedCamera.video.frameRate.ideal===30 && document.getElementById('video').srcObject?.active",'camera 30 fps choice');
  assert.equal(await evaluate("window.testTrack.readyState"),'ended');
  await evaluate("window.testTrack=document.getElementById('video').srcObject.getVideoTracks()[0]");
  await click('stop');
  assert.equal(await evaluate("window.testTrack.readyState"),'ended');
  assert.equal(await evaluate("document.getElementById('video').srcObject"),null);
  console.log('PASS: camera preview starts and Stop releases the track');
  await evaluate("document.getElementById('targetFps').value='60';document.getElementById('inputResolution').value='1280';document.getElementById('processingWidth').value='480';document.getElementById('maxPoints').value='250';document.getElementById('maxPoints').dispatchEvent(new Event('input'))");
  await evaluate("window.realGetUserMedia=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=()=>Promise.reject(new DOMException('Test denial','NotAllowedError'))");
  await click('start');
  await waitFor("document.getElementById('status').classList.contains('error') && document.getElementById('status').textContent.includes('許可')",'permission error');
  await evaluate("navigator.mediaDevices.getUserMedia=window.realGetUserMedia");
  console.log('PASS: permission denial has an actionable Japanese message');
  await evaluate("navigator.mediaDevices.getUserMedia=async (...args)=>{const stream=await window.realGetUserMedia(...args);window.lateStream=stream;await new Promise(r=>setTimeout(r,500));return stream;}");
  await click('start');await click('demo');
  await waitFor("window.lateStream?.getTracks().every(t=>t.readyState==='ended')",'cancelled camera cleanup');
  assert.equal(await evaluate("document.getElementById('sourceLabel').textContent"),'デモ / 動く図形');
  await evaluate("navigator.mediaDevices.getUserMedia=window.realGetUserMedia");
  console.log('PASS: switching to demo while permission is pending releases late streams');
  await runMediaSmoke({evaluate,send,click,waitFor,until,delay,artifacts,downloads});
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await delay(250);
  assert.equal(await evaluate('document.documentElement.scrollWidth <= window.innerWidth'),true);
  await writeFile(join(artifacts,'mobile-demo.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
  assert.deepEqual(errors,[]);
  console.log('PASS: mobile layout fits; no browser runtime errors');
  await runIPhoneSmoke({send,evaluate,click,waitFor,delay,artifacts});
  assert.deepEqual(errors,[]);
  await runPwaSmoke({send,evaluate,click,waitFor,artifacts});
  assert.deepEqual(errors,[]);
  console.log(`Screenshots and downloads: ${artifacts}`);
  await send('Browser.close').catch(()=>{});
} finally {
  ws?.close();browser?.kill();server.kill();
}
